repos:
  # hooks for backend
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.1
    hooks:
      # Run the linter.
      - id: ruff
        files: ./backend
        types: [python]
      # Run the formatter.
      - id: ruff-format